### ISSUE TITLE
Синтаксическая ошибка в модуле обработке

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/v83unpack#1]
В строке 1159 модуля обработки проекта v83unpack добавлен лишний знак "+"
Комментарий Артура:
фишка в чем, что мы счас юзаем абсолютный путь к файлу хранилища типа 
\REPO\project\1cv8ddb.1CD
в этом случае работает тулза Tool_1Cd, а блок с ошибкой (с лишним +) не работает

**Comment by pumbaEO** [comment]
77c104cb6adb5743c7ea0fed50cd8c2d80303c3d
