### ISSUE TITLE
git add -A

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/v83unpack#17]
Источник: http://stackoverflow.com/questions/572549/difference-between-git-add-a-and-git-add

Сейчас в коде стоит команда:
`git add .`
она означает "stages new and modified, **without deleted**"
т.е. удаленные файлы сюда не попадут.
Предлагаю исправить на 
`git add -A`
что означает " stages **All**"

**Comment by artbear** [comment]
Поддерживаю.
@pumbaEO что скажешь?
