### ISSUE TITLE
Можно сделать, чтоб пуш сразу делался?

### ISSUE THREAD

**Issue by Irekovich** [xDrivenDevelopment/v83unpack#21]
Может оно и есть, но мне приходится потом вручную это делать, после того как все коммиты закончились.

**Comment by pumbaEO** [comment]
Для автоматического push очень много неизвестных, push делать всех веток или текущей, куда делать push в origin, upstream или ее куда. 
Аутентификация какая, имя-пароль, ключ ssh, kerberos?

Синхронизацию запускаешь автоматом? Батником? Сервером сборок? 

у меня после задачи синхронизации отдельным шагом идут команды 

```
chcp 866
echo "GIT PUSH"
cd src
git push 
```

**Comment by artbear** [comment]
ИМХО эта задача давно назрела и даже выполнена в дополнениях сабжа.
В наших дополнениях (1С2Гит и в порте v83unpack для OneScript) я добился того, чтобы пуш делался автоматом после синхронизации всех новых версий.

**Comment by Irekovich** [comment]
Пока только тренеруюсь на маленьком хранилище в несколько коммитов. Сделал батник из одной команды как в примере https://github.com/xDrivenDevelopment/v83unpack/wiki/Параметры-коммандной-строки. Запускаю вручную. Потом автоматом будет.
git push пишет:

fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository us
ing

```
git remote add <name> <url>
```

and then push using the remote name

```
git push <name>
```

rtfm кароч

@artbear где посмотреть на это можно?

**Comment by ghost** [comment]
@Irekovich тебе нужно прописать куда push'ить

```
git remote set-url --push origin https://github.com/xDrivenDevelopment/test-bit-git.git
```

означает "установить адрес в качестве оригинального" 

но есть возможность проще
создай репозиторий на github Или bitbucket
сделай чистый clone

git clone https://<username>@bitbucket.org/<Username>/my-repo

и тогда разбирай туда конфигурацию и делай команду как @artbear написал

chcp 866
echo "GIT PUSH"
cd src
git push

**Comment by Irekovich** [comment]
Сделал git clone, потом git push.
Он у меня пароль просит.
Я пароль в файл записал и ему подсунул:
git push < e:\Repositories\pass.dat
Но видимо так нельзя, т.к. все равно пароль просит.
Как сделать, чтоб пароль не надо было вводить?

**Comment by kuntashov** [comment]
Настроить авторизацию по ssh-ключу, тогда пароль один раз только надо будет указывать при запуске агента ключей, либо вообще ssh-ключ без пароля сделать (но не рекомендуется).

**Comment by Irekovich** [comment]
ок поразбираюсь с ключами. спасибо.

**Comment by ghost** [comment]
@Irekovich - мы с артуром точно делали с паролем без ssh ключей. Правда не совсем помню как.

Но с ssh ключами круче - если у тебя Windows: то ставь putty.msi в него входит PAgent который будет хранить ключи авторизации

**Comment by Irekovich** [comment]
SendKeys не?
Если есть возможность без установки доп софта, то меня бы это больше устроило.

**Comment by Irekovich** [comment]
Попробовал. Вот так получилось
set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.Run "e:\Repositories\push.bat", 1
WScript.Sleep 2000
WshShell.AppActivate("C:\Windows\system32\cmd.exe")
WshShell.SendKeys("Password~")

**Comment by pumbaEO** [comment]
https://gitcredentialstore.codeplex.com/ 
утилита для запоминания паролей.
