### ISSUE TITLE
Обрезается "Код" в предопределенных элементах справочников

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/v83unpack#30]
У предопределенного элемента справочника строковый код "0000001  ". После выгрузки-загрузки в итоговом cf код оказывается равным "0000001" (без пробелов)

**Comment by pumbaEO** [comment]
Это особенность 1с, надо у них регистрировать ошибку.
01 июля 2015 г. 0:40 пользователь "Nikita Gryzlov" notifications@github.com
написал:

**Comment by pumbaEO** [comment]
Если есть тестовый пример, присылайте отошлем в 1с.

**Comment by nixel2007** [comment]
Хм, похоже я поторопился с диагнозом. Проблема на моей стороне.
Имеется конфигурация собранная изначально еще под 8.2. Был справочник, у которого длина кода была 9, потом была увеличена до 12. Соответственно в справочнике остался элемент с кодом "000000001   ".
Выгрузив конфу в файлы и открыв predefined.xml я так же вижу там "000000001   ".
Если собрать cf-ник, то в нем код будет так же "000000001   ", однако же сравнение конфигураций будет показывать различия.
НО!
Если зайти в этот предопределенный элемент и просто перезаписать код, ничего в нем не изменив, то потом сравнение уже не будет показывать различий. Видимо, за годы несколько изменился способ/принцип хранения пробелов в кодах справочников.

Резюмируя: проблема не в v83unpack - это запланированное поведение платформы.
К слову, вылечить можно загрузкой/выгрузкой конфигурации в xml - после этого отличий нет. И 1с рекомендовала старые конфигурации выгружать/загружать для удаления ошибочной информации в файлах cf.
