### ISSUE TITLE
Ошибка синхронизации хранилища с git

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/v83unpack#4]
При нажатии на кнопку "Синхронизировать хранилище с гит" вываливается исключение:

> {ВнешняяОбработка.ВыгрузкаКонфигурации1С.МодульОбъекта(2885)}: Переданный параметр (Нет) не является Истиной, а хотели, чтобы являлся.
> Не заполнен комментарий. 2
>         ВызватьИсключение(СообщениеОшибки);

Включена отладка, вот ее содержимое:

> "C:\Temp\6\Tool_1CD.09cb9b6b-1f96-429c-b28a-ba2966d3263e.exe" D:\1S2Git\1s_repo\DEV_SED_STORE\1cv8ddb.1CD -q -ne -ex D:\1S2Git\tmp\v83up_a660283e-019d-48a6-843e-884973d65d00.tmp\ VERSIONS;USERS
> VERSION {

Вот скрин настроек:
http://screencast.com/t/S6ew85dgTf9v

Папка "D:\1S2Git\DEV_SED_STORE\" непуста, там уже лежит одна версия сорцов. Помещал вручную (скорее всего именно из-за этого ошибка и вываливается), потому как автоматом выдавало другую ошибку при первом помещении:

> {ВнешняяОбработка.ВыгрузкаКонфигурации1С.МодульОбъекта(2885)}: Переданный параметр (Нет) не является Истиной, а хотели, чтобы являлся.
> синхронизация с Git, версия <1> - не удалось выполнить ВыполнитьКоммитГит
>         ВызватьИсключение(СообщениеОшибки);

Полный лог первого помещения:

```
"C:\Temp\6\Tool_1CD.5ce23aa0-dd05-4557-a6bb-46dfd829593b.exe" D:\1S2Git\1s_repo\DEV_SED_STORE\1cv8ddb.1CD -q -ne -ex D:\1S2Git\tmp\v83up_af46ad87-df66-4394-abe8-eb0cfde0222b.tmp\ VERSIONS;USERS
Начало 15.07.2014 16:55:13
"C:\Temp\6\Tool_1CD.54d575f6-3a47-413a-b1ba-2ec51ed459ea.exe" "D:\1S2Git\1s_repo\DEV_SED_STORE\1cv8ddb.1CD" -q -ne -drc 1 "D:\1S2Git\tmp\v83up_c0ac1912-bf64-47d7-831c-b5701235d349\v1.cf"
Начало создать базу 15.07.2014 16:55:28
"C:\Program Files (x86)\1cv8\8.3.4.437\bin\1cv8.exe" CREATEINFOBASE  File="D:\1S2Git\tmp\v83up_4bf98c9a-6c3f-4f22-9fce-5a2c28c496ab" /Lru /Out "D:\1S2Git\tmp\app_0283577c-30da-4b01-918c-a113dfe4eeeb.log"
"C:\Program Files (x86)\1cv8\8.3.4.437\bin\1cv8.exe" DESIGNER  /F "D:\1S2Git\tmp\v83up_4bf98c9a-6c3f-4f22-9fce-5a2c28c496ab" /LoadCfg"D:\1S2Git\tmp\v83up_c0ac1912-bf64-47d7-831c-b5701235d349\v1.cf" /Lru /Out "D:\1S2Git\tmp\app_0283577c-30da-4b01-918c-a113dfe4eeeb.log"
Завершение: создать базу 15.07.2014 16:57:25
ВыгрузитьМодули: команда "C:\Program Files (x86)\1cv8\8.3.4.437\bin\1cv8.exe" DESIGNER  /F "D:\1S2Git\tmp\v83up_4bf98c9a-6c3f-4f22-9fce-5a2c28c496ab"  /Visible /DumpConfigToFiles"D:\1S2Git\tmp\v83up_79df8e92-3f6c-4587-94ca-16c97ff777f8" /Lru /Out"D:\1S2Git\tmp\app_3c060d3f-7d8f-419e-9db3-161b8e3e6491.log"
РазложитьМодули1СПоПапкамСогласноИерархииМетаданных: команда taskkill /im TGitCache.exe  /T /F
Слишком длинное имя:ИспользоватьДополнительныеОтчетыИОбработкиСозданиеСвязанныхОбъектов длина:67
Старое имя:ИспользоватьДополнительныеОтчетыИОбработкиСозданиеСвязанныхОбъектов новое имя:ИспользоватьДополнительныеОтчетыИОбработкиСозданиеСвяза~67
Слишком длинное имя:ИспользоватьДополнительныеОтчетыИОбработкиСозданиеСвязанныхОбъектов длина:67
Старое имя:ИспользоватьДополнительныеОтчетыИОбработкиСозданиеСвязанныхОбъектов новое имя:ИспользоватьДополнительныеОтчетыИОбработкиСозданиеСвяза~67
Завершение 15.07.2014 17:00:55, Общее время: 5,7 мин.
ВыполнитьКоммитГит: команда D:\1S2Git\tmp\v83up_e6dc6570-e834-4040-a489-e76ca169b1bd.bat
ВыполнитьКоммитГит: текст файла запуска 
cd /d "D:\1S2Git\DEV_SED_STORE\"
set GIT_AUTHOR_DATE="2013-05-15 05:02:36"
git add .
git commit -a --file="D:\1S2Git\tmp\v83up_c411a9d8-f4ea-4918-8846-4c65bd367879.txt" --author="Тестовый <test@test.ru>" >D:\1S2Git\tmp\v83up_2ebfae98-8576-4b1a-968e-a737d12c3c70.log
exit /b %ERRORLEVEL%

ВыполнитьКоммитГит: Вызов git commit вернул код <9 009> 
ВыполнитьКоммитГит: Не удалось получить лог команды git commit
```

В общем прошу что-нибудь сделать, чтобы работало.

**Comment by artbear** [comment]
Похоже, нужно все-таки выложить мою версию обработки из проекта 1С2Гит :)
Там часть ошибок поправлена.

**Comment by artbear** [comment]
Подозреваю, что у тебя при коммите в хранилище 1С не был заполнен комментарий.
Посмотри историю хранилища.
Ты же выгружаешь версию с номером 1, верно?
Ее в истории хранилища и смотри.
ЗЫ для 1С2Гит я эту ошибку с пустым комментом поправил - вместо пустого комментария автоматом вставляется точка.

**Comment by JohnyDeath** [comment]
Пустой комментарий даже я правил: https://github.com/pumbaEO/v83unpack/commit/74f0ac4c713c7dae11ec96085add501f5eccdb89 :smile:
В тот период я работал с другим хранилищем. Оно было под 8.2. Не знаю, с этим связано или нет, но сейчас что-то все со скрипом продвигается.
Выложи свою из 1С2Гит, если не сложно (вместе с самим сервером :smirk: ) .

**Comment by JohnyDeath** [comment]
Решение: https://github.com/xDrivenDevelopment/v83unpack/issues/5
